--xuat ra cac pid trong SP
SELECT PID FROM S_P_SP.dbo.SP
--xuat ra cac pid va rut gon cac trung lap
SELECT distinct PID FROM S_P_SP.dbo.SP

--sid va so luong mat hang da ban
SELECT SID, Quantity FROM S_P_SP.dbo.SP

--dua ra ttin hang cung ung co ten Sant hay Santa
SELECT *FROM S WHERE Sname LIKE '%San%'
 
--DUA RA SNAME CUA CAC HANG DA BAN MAT HANG P2
SELECT Sname FROM S,SP WHERE (S.SID = SP.SID) AND (PID ='P2')

--DUA RA TEN VA DIACHI CUA CAC HANG CUNG UNG CO STATUS>100
SELECT Sname, City AS Address FROM S WHERE (Status>100)

--DUA RA SID CUA CAC HANG DA BAN CA 2 MAT HANG P1 VA P2
SELECT T1.SID FROM SP AS T1, SP AS T2 WHERE (T1.SID = T2.SID) AND (T1.PID = 'P1') AND (T2.PID = 'P2')
			   /*T1 la ban sao cua T2*/

--TIM TEN PNAME VA PID CUA CAC MAT HANG MAU DO, SAP XEP THEO THU TU GIAM DAN CUA PID
--ORDER BY: SAP XEP
SELECT * FROM P WHERE(Color = 'red')
ORDER BY PID DESC; /*DESC: giam dan
				   	 ASC: tang dan*/

--GROUP BY: TIM KIEM
--TIM SID CUNG CAP CA 2 MAT HANG P1 VA P2
SELECT SID FROM SP GROUP BY SID HAVING SET (PID) CONTAINT('P1','P2')
SELECT SID FROM SP GROUP BY SID HAVING COUNT (PID) >= 2

--SO SANH: SU DUNG IN(truy van con)
--SU DUNG IN, TIM MA SID,SNAME CAC HANG DA BAN MAT HANG P2
SELECT SID,Sname FROM S WHERE SID IN (SELECT SID FROM SP WHERE PID ='P2')
